spring.application.name=taskhub

spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5433}/${POSTGRES_DB:taskhub}
spring.datasource.username=${POSTGRES_USER:taskhub}
spring.datasource.password=${POSTGRES_PASSWORD:taskhub}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

app.jwt.secret=very-secret-development-key-very-secret-development-key
app.jwt.expiration-ms=86400000